import type { Driver, FleetVehicle, KpiData, Notification, MapMarker } from "@shared/schema";

export const mockKpis: KpiData = {
  onTimeRate: 92,
  dropsPerRoute: 14,
  totalDistance: 142,
  fuelSavings: 18,
  co2Reduction: 24,
};

export const mockDrivers: Driver[] = [
  {
    id: "d1",
    name: "Murugan Selvam",
    homeLocality: "T. Nagar",
    vehicleType: "bike",
    status: "active",
    currentRoute: "Route A-12",
    dropsCompleted: 9,
    dropsTotal: 14,
    fuelConsumption: 2.1,
    phone: "+91 98765 43210",
    avatar: "MS",
  },
  {
    id: "d2",
    name: "Kavitha Lakshmi",
    homeLocality: "Anna Nagar",
    vehicleType: "van",
    status: "active",
    currentRoute: "Route B-07",
    dropsCompleted: 12,
    dropsTotal: 16,
    fuelConsumption: 8.4,
    phone: "+91 98765 43211",
    avatar: "KL",
  },
  {
    id: "d3",
    name: "Senthil Kumaran",
    homeLocality: "Adyar",
    vehicleType: "bike",
    status: "idle",
    currentRoute: "Route C-03",
    dropsCompleted: 14,
    dropsTotal: 14,
    fuelConsumption: 1.8,
    phone: "+91 98765 43212",
    avatar: "SK",
  },
  {
    id: "d4",
    name: "Meenakshi Sundaram",
    homeLocality: "Velachery",
    vehicleType: "van",
    status: "active",
    currentRoute: "Route D-09",
    dropsCompleted: 6,
    dropsTotal: 12,
    fuelConsumption: 9.2,
    phone: "+91 98765 43213",
    avatar: "MS",
  },
  {
    id: "d5",
    name: "Karthikeyan Rajan",
    homeLocality: "Mylapore",
    vehicleType: "bike",
    status: "offline",
    currentRoute: "—",
    dropsCompleted: 0,
    dropsTotal: 0,
    fuelConsumption: 0,
    phone: "+91 98765 43214",
    avatar: "KR",
  },
  {
    id: "d6",
    name: "Tamilselvi Nadar",
    homeLocality: "Tambaram",
    vehicleType: "van",
    status: "active",
    currentRoute: "Route E-15",
    dropsCompleted: 10,
    dropsTotal: 18,
    fuelConsumption: 11.3,
    phone: "+91 98765 43215",
    avatar: "TN",
  },
];

export const mockFleet: FleetVehicle[] = [
  {
    id: "v1",
    type: "bike",
    licensePlate: "TN-01-AB-1234",
    driverId: "d1",
    driverName: "Murugan Selvam",
    status: "en-route",
    location: { lat: 13.0418, lng: 80.2341 },
    fuelLevel: 72,
    currentArea: "T. Nagar",
  },
  {
    id: "v2",
    type: "van",
    licensePlate: "TN-01-CD-5678",
    driverId: "d2",
    driverName: "Kavitha Lakshmi",
    status: "en-route",
    location: { lat: 13.0850, lng: 80.2101 },
    fuelLevel: 45,
    currentArea: "Anna Nagar",
  },
  {
    id: "v3",
    type: "bike",
    licensePlate: "TN-01-EF-9012",
    driverId: "d3",
    driverName: "Senthil Kumaran",
    status: "idle",
    location: { lat: 13.0012, lng: 80.2565 },
    fuelLevel: 88,
    currentArea: "Adyar",
  },
  {
    id: "v4",
    type: "van",
    licensePlate: "TN-01-GH-3456",
    driverId: "d4",
    driverName: "Meenakshi Sundaram",
    status: "en-route",
    location: { lat: 12.9816, lng: 80.2185 },
    fuelLevel: 31,
    currentArea: "Velachery",
  },
  {
    id: "v5",
    type: "bike",
    licensePlate: "TN-01-IJ-7890",
    driverId: "d5",
    driverName: "Karthikeyan Rajan",
    status: "maintenance",
    location: { lat: 13.0368, lng: 80.2676 },
    fuelLevel: 100,
    currentArea: "Mylapore",
  },
  {
    id: "v6",
    type: "van",
    licensePlate: "TN-01-KL-2345",
    driverId: "d6",
    driverName: "Tamilselvi Nadar",
    status: "en-route",
    location: { lat: 12.9249, lng: 80.1000 },
    fuelLevel: 56,
    currentArea: "Tambaram",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "late-delivery",
    severity: "high",
    driverName: "Meenakshi Sundaram",
    message: "Delivery #4892 delayed by 22 minutes at Velachery drop point",
    timestamp: "2 min ago",
    acknowledged: false,
  },
  {
    id: "n2",
    type: "overtime-alert",
    severity: "high",
    driverName: "Kavitha Lakshmi",
    message: "Exceeded 9-hour shift limit. Currently at 9h 34m",
    timestamp: "8 min ago",
    acknowledged: false,
  },
  {
    id: "n3",
    type: "route-deviation",
    severity: "medium",
    driverName: "Murugan Selvam",
    message: "Deviated 1.2 km from planned route near Mount Road",
    timestamp: "15 min ago",
    acknowledged: false,
  },
  {
    id: "n4",
    type: "vehicle-issue",
    severity: "low",
    driverName: "Karthikeyan Rajan",
    message: "Bike TN-01-IJ-7890 scheduled for maintenance today",
    timestamp: "1 hr ago",
    acknowledged: true,
  },
  {
    id: "n5",
    type: "late-delivery",
    severity: "medium",
    driverName: "Tamilselvi Nadar",
    message: "Delivery #4901 at risk — traffic congestion on GST Road",
    timestamp: "1 hr ago",
    acknowledged: true,
  },
];

export const mockMapMarkers: MapMarker[] = mockFleet.map((v) => ({
  id: v.id,
  type: v.type,
  driverName: v.driverName,
  position: v.location,
  status: v.status,
}));
